/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as StoreRouteImport } from './routes/store'
import { Route as AuditSessionIdRouteImport } from './routes/audit/$sessionId'
import { Route as ApiPublicAgentCatalogRouteImport } from './routes/api/public/agent/catalog'
import { Route as ApiPublicAgentManifestRouteImport } from './routes/api/public/agent/manifest'
import { Route as ApiPublicAgentNegotiateRouteImport } from './routes/api/public/agent/negotiate'
import { Route as ApiPublicAgentOrderRouteImport } from './routes/api/public/agent/order'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditSessionIdRoute = AuditSessionIdRouteImport.update({
  id: '/audit/$sessionId',
  path: '/audit/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCatalogRoute = ApiPublicAgentCatalogRouteImport.update({
  id: '/api/public/agent/catalog',
  path: '/api/public/agent/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentManifestRoute = ApiPublicAgentManifestRouteImport.update({
  id: '/api/public/agent/manifest',
  path: '/api/public/agent/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentNegotiateRoute = ApiPublicAgentNegotiateRouteImport.update({
  id: '/api/public/agent/negotiate',
  path: '/api/public/agent/negotiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentOrderRoute = ApiPublicAgentOrderRouteImport.update({
  id: '/api/public/agent/order',
  path: '/api/public/agent/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay/webhook',
    path: '/api/public/razorpay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/merchant': typeof MerchantRoute
  '/store': typeof StoreRoute
  '/audit/$sessionId': typeof AuditSessionIdRoute
  '/api/public/agent/catalog': typeof ApiPublicAgentCatalogRoute
  '/api/public/agent/manifest': typeof ApiPublicAgentManifestRoute
  '/api/public/agent/negotiate': typeof ApiPublicAgentNegotiateRoute
  '/api/public/agent/order': typeof ApiPublicAgentOrderRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/merchant': typeof MerchantRoute
  '/store': typeof StoreRoute
  '/audit/$sessionId': typeof AuditSessionIdRoute
  '/api/public/agent/catalog': typeof ApiPublicAgentCatalogRoute
  '/api/public/agent/manifest': typeof ApiPublicAgentManifestRoute
  '/api/public/agent/negotiate': typeof ApiPublicAgentNegotiateRoute
  '/api/public/agent/order': typeof ApiPublicAgentOrderRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/merchant': typeof MerchantRoute
  '/store': typeof StoreRoute
  '/audit/$sessionId': typeof AuditSessionIdRoute
  '/api/public/agent/catalog': typeof ApiPublicAgentCatalogRoute
  '/api/public/agent/manifest': typeof ApiPublicAgentManifestRoute
  '/api/public/agent/negotiate': typeof ApiPublicAgentNegotiateRoute
  '/api/public/agent/order': typeof ApiPublicAgentOrderRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/merchant'
    | '/store'
    | '/audit/$sessionId'
    | '/api/public/agent/catalog'
    | '/api/public/agent/manifest'
    | '/api/public/agent/negotiate'
    | '/api/public/agent/order'
    | '/api/public/razorpay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/merchant'
    | '/store'
    | '/audit/$sessionId'
    | '/api/public/agent/catalog'
    | '/api/public/agent/manifest'
    | '/api/public/agent/negotiate'
    | '/api/public/agent/order'
    | '/api/public/razorpay/webhook'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/merchant'
    | '/store'
    | '/audit/$sessionId'
    | '/api/public/agent/catalog'
    | '/api/public/agent/manifest'
    | '/api/public/agent/negotiate'
    | '/api/public/agent/order'
    | '/api/public/razorpay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  MerchantRoute: typeof MerchantRoute
  StoreRoute: typeof StoreRoute
  AuditSessionIdRoute: typeof AuditSessionIdRoute
  ApiPublicAgentCatalogRoute: typeof ApiPublicAgentCatalogRoute
  ApiPublicAgentManifestRoute: typeof ApiPublicAgentManifestRoute
  ApiPublicAgentNegotiateRoute: typeof ApiPublicAgentNegotiateRoute
  ApiPublicAgentOrderRoute: typeof ApiPublicAgentOrderRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/$sessionId': {
      id: '/audit/$sessionId'
      path: '/audit/$sessionId'
      fullPath: '/audit/$sessionId'
      preLoaderRoute: typeof AuditSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/catalog': {
      id: '/api/public/agent/catalog'
      path: '/api/public/agent/catalog'
      fullPath: '/api/public/agent/catalog'
      preLoaderRoute: typeof ApiPublicAgentCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/manifest': {
      id: '/api/public/agent/manifest'
      path: '/api/public/agent/manifest'
      fullPath: '/api/public/agent/manifest'
      preLoaderRoute: typeof ApiPublicAgentManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/negotiate': {
      id: '/api/public/agent/negotiate'
      path: '/api/public/agent/negotiate'
      fullPath: '/api/public/agent/negotiate'
      preLoaderRoute: typeof ApiPublicAgentNegotiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/order': {
      id: '/api/public/agent/order'
      path: '/api/public/agent/order'
      fullPath: '/api/public/agent/order'
      preLoaderRoute: typeof ApiPublicAgentOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay/webhook': {
      id: '/api/public/razorpay/webhook'
      path: '/api/public/razorpay/webhook'
      fullPath: '/api/public/razorpay/webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  MerchantRoute: MerchantRoute,
  StoreRoute: StoreRoute,
  AuditSessionIdRoute: AuditSessionIdRoute,
  ApiPublicAgentCatalogRoute: ApiPublicAgentCatalogRoute,
  ApiPublicAgentManifestRoute: ApiPublicAgentManifestRoute,
  ApiPublicAgentNegotiateRoute: ApiPublicAgentNegotiateRoute,
  ApiPublicAgentOrderRoute: ApiPublicAgentOrderRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
